services:
  backend:
    build: 
      dockerfile: ./Dockerfile
      context: ./packages/backend
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules 
    networks:
      - app-network

  frontend:
    build: 
      dockerfile: ./Dockerfile
      context: ./packages/frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - /app/node_modules
networks:
  app-network:
    driver: bridge