name: Backend Coverage

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  backend-coverage:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Clone repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js version
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Fija una versión para garantizar consistencia

      # Step 3: Start MongoDB
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: '5.0'

      # Step 4: Install dependencies
      - name: Install Dependencies
        run: npm install
        working-directory: packages/backend

      # Step 5: Set environment variables
      - name: Set Environment Variables
        run: |
          echo "MONGODB_URL=mongodb://localhost:27017/test" >> $GITHUB_ENV
          echo "COVERALLS_REPO_TOKEN=${{ secrets.COVERALLS_REPO_TOKEN }}" >> $GITHUB_ENV

      # Step 6: Run Coverage and Upload to Coveralls
      - name: Run Coverage and Upload to Coveralls
        env:
          MONGODB_URL: ${{ env.MONGODB_URL }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: npm run coverage
        working-directory: packages/backend

      # Step 7: Upload coverage report to Coveralls
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        working-directory: packages/backend
